# Generated by Django 4.0.2 on 2022-02-21 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CasesPerCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collected', models.TextField()),
                ('death_numbers', models.IntegerField(blank=True, null=True)),
                ('case_numbers', models.IntegerField(blank=True, null=True)),
                ('recovery_numbers', models.IntegerField(blank=True, null=True)),
                ('hospitalization_numbers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cases_Per_Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CasesPerDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collected', models.TextField()),
                ('death_numbers', models.IntegerField(blank=True, null=True)),
                ('case_numbers', models.IntegerField(blank=True, null=True)),
                ('recovery_numbers', models.IntegerField(blank=True, null=True)),
                ('hospitalization_numbers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cases_Per_District',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CasesPerRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collected', models.TextField()),
                ('death_numbers', models.IntegerField(blank=True, null=True)),
                ('case_numbers', models.IntegerField(blank=True, null=True)),
                ('recovery_numbers', models.IntegerField(blank=True, null=True)),
                ('hospitalization_numbers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cases_Per_Region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'Countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('district_code', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=128)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('region_code', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=128)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_information', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'Sources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationPerCountry',
            fields=[
                ('country_code', models.OneToOneField(db_column='country_code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.countries')),
                ('population_amount', models.BigIntegerField()),
                ('date_collected', models.TextField()),
            ],
            options={
                'db_table': 'Population_Per_Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationPerDistrict',
            fields=[
                ('district_code', models.OneToOneField(db_column='district_code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.districts')),
                ('population_amount', models.BigIntegerField()),
                ('date_collected', models.TextField()),
            ],
            options={
                'db_table': 'Population_Per_District',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationPerRegion',
            fields=[
                ('region_code', models.OneToOneField(db_column='region_code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.regions')),
                ('population_amount', models.BigIntegerField()),
                ('date_collected', models.TextField()),
            ],
            options={
                'db_table': 'Population_Per_Region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinationsPerCountry',
            fields=[
                ('first_vaccination_rate', models.TextField()),
                ('second_vaccination_rate', models.TextField()),
                ('third_vaccination_rate', models.TextField()),
                ('country_code', models.OneToOneField(db_column='country_code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.countries')),
            ],
            options={
                'db_table': 'Vaccinations_Per_Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinationsPerDistrict',
            fields=[
                ('first_vaccination_rate', models.TextField()),
                ('second_vaccination_rate', models.TextField()),
                ('third_vaccination_rate', models.TextField()),
                ('district_code', models.OneToOneField(db_column='district_code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.districts')),
            ],
            options={
                'db_table': 'Vaccinations_Per_District',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinationsPerRegion',
            fields=[
                ('first_vaccination_rate', models.TextField()),
                ('second_vaccination_rate', models.TextField()),
                ('third_vaccination_rate', models.TextField()),
                ('region_code', models.OneToOneField(db_column='region_code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.regions')),
            ],
            options={
                'db_table': 'Vaccinations_Per_Region',
                'managed': False,
            },
        ),
    ]
