# Generated by Django 4.0.2 on 2022-02-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='CasesPerCountry',
        ),
        migrations.DeleteModel(
            name='CasesPerDistrict',
        ),
        migrations.DeleteModel(
            name='CasesPerRegion',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.RemoveField(
            model_name='populationpercountry',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='populationperdistrict',
            name='district_code',
        ),
        migrations.RemoveField(
            model_name='populationperregion',
            name='region_code',
        ),
        migrations.DeleteModel(
            name='Sources',
        ),
        migrations.RemoveField(
            model_name='vaccinationspercountry',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='vaccinationsperdistrict',
            name='district_code',
        ),
        migrations.RemoveField(
            model_name='vaccinationsperregion',
            name='region_code',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='Districts',
        ),
        migrations.DeleteModel(
            name='PopulationPerCountry',
        ),
        migrations.DeleteModel(
            name='PopulationPerDistrict',
        ),
        migrations.DeleteModel(
            name='PopulationPerRegion',
        ),
        migrations.DeleteModel(
            name='Regions',
        ),
        migrations.DeleteModel(
            name='VaccinationsPerCountry',
        ),
        migrations.DeleteModel(
            name='VaccinationsPerDistrict',
        ),
        migrations.DeleteModel(
            name='VaccinationsPerRegion',
        ),
    ]
